name: bicycle_app_technician
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^3.1.0
  get: ^4.7.3
  pinput: ^6.0.2
  image_picker: ^1.2.1
  share_plus: ^12.0.1
  table_calendar: ^3.0.9
  http: ^1.6.0
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  number_to_words: ^1.0.0
  lottie: ^3.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
